### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by veluriy** [rp-agota/auto-build#21]
readme.mdのSTEP1のURLが違う気がする
`git clone https://github.com/rp-agota/auto-build.git` かな

**Comment by veluriy** [comment]
Windows10にUbuntuとかいうのがあったので起動してみたらUbuntuサーバーだったので使ってみてる。

**Comment by veluriy** [comment]
そういえばこれバージョンアップした時ってどう使うのが良いかな？

**Comment by admidori** [comment]
URLの件は申し訳ない！修正しました。
とりあえずアップデート機能を試験中なのでちょっと待ってて欲しい。多分すぐ完成する。

**Comment by veluriy** [comment]
おっけー
アプデ機能普通にありがてえな
