### ISSUE TITLE
about languages

### ISSUE THREAD

**Issue by veluriy** [rp-agota/auto-build#5]
どういった言語を追加する予定を考えてる？

**Comment by admidori** [comment]
@yamaxa 
ALGOL,PL/I,Java,C++,Go,Haskell・・・辺りのコンパイル型言語は実装しやすいし（僕が興味あるし）確実に追加すると思う。

Pythonだとかのインタプリタ型も実装したいけどちょっと厄介そうなのでとりあえずはコンパイル型言語優先かな〜

**Comment by veluriy** [comment]
コンパイル言語の時点で欲しいやつ複数個あるな
ともかく頑張って〜

**Comment by admidori** [comment]
**追記**
と言うことでC++を追加しました。後はdocker-compose変えながら対応言語増やしていくだけなので多分コンパイル型言語は大方対応できるようになると思う。
beta1.0 -> #14
